[build]
	functions = "netlify_functions"
	publish = "frontend/"
	
[dev]
	dir = "frontend/"
	command = "live-server --port=5500 --no-browser"
	targetPort = 5500
	framework = "#custom"
	publish = "frontend/"
	
[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200
